[package]
name = "harvest_fa"
version = "1.0.0"
authors = []

[addresses]
harvest = "0x1a7ac6e9638f159b4dab0eead15605d21ed728fc301d1042ae8a5f4f5a010c7d"
stake_emergency_admin = "0x1a7ac6e9638f159b4dab0eead15605d21ed728fc301d1042ae8a5f4f5a010c7d"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dependencies.AptosToken]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token"

